

gnao1_chromosome = "16"

gnao1_cdna = '''
ATGGGATGTACTCTGAGCGCAGAGGAGAGAGCCGCCCTCGAGCGGAGCAAGGCGATTGAGAAAAACCTCAAAGAGGATGGCATCAGCGCCGCCAAAGACG
TGAAATTACTCCTGCTCGGGGCTGGAGAATCAGGAAAAAGCACCATTGTGAAGCAGATGAAGATCATCCATGAAGATGGCTTCTCCGGAGAAGACGTGAA
ACAGTACAAGCCTGTTGTCTACAGCAACACTATCCAGTCCCTGGCAGCCATCGTCCGGGCCATGGACACTTTGGGCATCGAATATGGTGATAAGGAGAGA
AAGGCTGACGCCAAGATGGTGTGTGATGTGGTGAGTCGGATGGAAGACACCGAGCCCTTCTCTGCAGAGCTGCTTTCTGCCATGATGCGGCTCTGGGGCG
ACTCAGGAATCCAAGAGTGCTTCAACCGGTCCCGGGAGTATCAGCTCAACGACTCTGCCAAATACTACCTGGACAGCCTGGATCGGATTGGGGCCGCCGA
CTACCAGCCCACCGAGCAGGACATCCTCCGAACCAGGGTCAAAACCACTGGCATCGTAGAAACCCACTTCACATTCAAGAACCTCCACTTCAGGCTGTTT
GACGTCGGAGGCCAGCGATCTGAACGCAAGAAGTGGATCCATTGCTTCGAGGACGTCACGGCCATCATTTTCTGTGTCGCGCTCAGCGGCTATGACCAGG
TGCTCCACGAAGACGAAACCACGAACCGCATGCACGAATCCCTGAAGCTTTTTGACAGCATCTGCAACAACAAATGGTTCACAGACACGTCCATCATCCT
GTTTCTTAACAAGAAGGACATATTTGAAGAGAAGATCAAGAAGTCCCCGCTCACCATCTGCTTTCCTGAATATACAGGCCCCAGCGCCTTCACAGAAGCC
GTGGCTTACATCCAGGCCCAGTACGAGAGCAAGAACAAGTCAGCCCACAAAGAGATCTACACCCACGTCACCTGCGCCACGGACACCAACAACATCCAGT
TTGTCTTTGATGCTGTGACGGACGTCATCATCGCCAAAAACCTGCGGGGCTGTGGACTCTACTGA
'''

gnao1_protein =  '''
MGCTLSAEERAALERSKAIEKNLKEDGISAAKDVKLLLLGAGESGKSTIVKQMKIIHEDGFSGEDVKQYKPVVYSNTIQSLAAIVRAMDTLGIEYGDKER
KADAKMVCDVVSRMEDTEPFSAELLSAMMRLWGDSGIQECFNRSREYQLNDSAKYYLDSLDRIGAADYQPTEQDILRTRVKTTGIVETHFTFKNLHFRLF
DVGGQRSERKKWIHCFEDVTAIIFCVALSGYDQVLHEDETTNRMHESLKLFDSICNNKWFTDTSIILFLNKKDIFEEKIKKSPLTICFPEYTGPSAFTEA
VAYIQAQYESKNKSAHKEIYTHVTCATDTNNIQFVFDAVTDVIIAKNLRGCGLY*
'''

gnao1_donor_splice = {   118: 'GTAAGGACCGCCGC',
    161: 'GTAAGTCCCTGTGG',
    303: 'GTAGGCCCCTGAGC',
    464: 'GTGAGTGTCCCAGC',
    593: 'GTGAGGCCCAGAGA',
    723: 'GTGAGTGGCCTGGG',
    877: 'GTAGAGACCCCTCC',
    1065: 'GCCCAGCCGCCCTG'}

gnao1_acceptor_splice = {   1: 'AGGGAAGGGGCCACC',
    119: 'TCTGTGTCCCAACAG',
    162: 'GTGGTTTTTCTCTAG',
    304: 'CACCTCTCCTCACAG',
    465: 'TGTTGCCATCCTCAG',
    594: 'CCCTGCCTCCTACAG',
    724: 'TCCACTCTGTTGCAG',
    878: 'CTGTTTGCTCTGCAG'}

gnao1_cdna2gdna = {   1: 56192236,
    118: 56192353,
    119: 56192574,
    161: 56192616,
    162: 56275931,
    303: 56276072,
    304: 56328631,
    464: 56328791,
    465: 56334729,
    593: 56334857,
    594: 56336731,
    723: 56336860,
    724: 56340834,
    877: 56340987,
    878: 56343763,
    1065: 56343950}

def get_cdna():
	return gnao1_cdna.replace("\n", "")
	
def get_protein():
	return gnao1_protein.replace("\n", "")
	
def get_codons():
	return [gnao1_cdna[i:i+3] for i in range(0,len(gnao1_cdna),3)]
	
def get_backward_numbered_acceptor_splice(bdry_pos):
	cumulative_length = max(gnao1_acceptor_splice.keys())
	return gnao1_acceptor_splice.get(cumulative_length-bdry_pos, None)
	
def get_backward_numbered_donor_splice(bdry_pos):
	cumulative_length = max(gnao1_donor_splice.keys())
	return gnao1_donor_splice.get(cumulative_length-bdry_pos, None)

